export {default as Navbar} from "../components/navbar/Navbar"
export {default as Main} from "../components/main/Main"
export {default as Cabinet} from "../components/cabinet/Cabinet"
export {default as Register} from "../components/register/Register"
export {default as ReviewerCabinet } from "../components/reviewer/ReviewerCabinet"
export { default as DocumentsList } from "../components/document/DocumentsList"
